[package]
name = "first-rust-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.17.0"

[dev-dependencies]
test-case = "2.0.2"
